import { IVacancy } from '@/shared/types/vacancy.types';
export const arrayVacancy: IVacancy[] = [
    {
        id: 'knsdb',
        title: 'Backend',
        position: 'Middle',
        location: 'Бишкек',
        description: 'Нужен фронт',
        isArchived: false,
        userId: 'njsdvjfb',
        salary: '',
        createdAt: 'c',
        updatedAt: '',
        user: {
            name: 'Мой О!',
            lastName: '',
            username: 'nfjv',
            avatarUrl: 'vknf',
        },
    },
    {
        id: 'kncasdb',
        title: 'UI/UX Designer',
        position: 'Junior',
        location: 'Бишкек',
        description: 'Нужен фронт',
        isArchived: false,
        userId: 'njsdvjfb',
        salary: 'от 40000 - 80000 сом',
        createdAt: 'c',
        updatedAt: '',
        user: {
            name: 'Mbank',
            lastName: '',
            username: 'nfjv',
            avatarUrl: 'vknf',
        },
    },
    {
        id: 'XCompany',
        title: 'Java Developer',
        position: 'Senior',
        location: 'Бишкек',
        description: 'Нужен фронт',
        isArchived: false,
        userId: 'njsdvjfb',
        salary: '5000$',
        createdAt: 'c',
        updatedAt: '',
        user: {
            name: 'XCompany',
            lastName: '',
            username: 'nfjv',
            avatarUrl: 'vknf',
        },
    },
    {
        id: 'knscdb',
        title: 'Python Developer',
        position: 'Middle+',
        location: 'Бишкек',
        description: 'Нужен фронт',
        isArchived: false,
        userId: 'njsdvjfb',
        salary: 'от 2000$',
        createdAt: 'c',
        updatedAt: '',
        user: {
            name: 'GoMax',
            lastName: '',
            username: 'nfjv',
            avatarUrl: 'vknf',
        },
    },
    {
        id: 'knscdb',
        title: 'Fullstack Developer React + C#',
        position: 'Intern',
        location: 'Бишкек',
        description: 'Нужен фронт',
        isArchived: false,
        userId: 'njsdvjfb',
        salary: '5000$ - 10000$',
        createdAt: 'c',
        updatedAt: '',
        user: {
            name: 'Google',
            lastName: '',
            username: 'nfjv',
            avatarUrl: 'vknf',
        },
    },
];
